// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kyve/registry/v1beta1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the set of params for the registry module.
type Params struct {
	// vote_slash ...
	VoteSlash string `protobuf:"bytes,3,opt,name=vote_slash,json=voteSlash,proto3" json:"vote_slash,omitempty"`
	// upload_slash ...
	UploadSlash string `protobuf:"bytes,4,opt,name=upload_slash,json=uploadSlash,proto3" json:"upload_slash,omitempty"`
	// timeout_slash ...
	TimeoutSlash string `protobuf:"bytes,5,opt,name=timeout_slash,json=timeoutSlash,proto3" json:"timeout_slash,omitempty"`
	// upload_timeout ...
	UploadTimeout uint64 `protobuf:"varint,6,opt,name=upload_timeout,json=uploadTimeout,proto3" json:"upload_timeout,omitempty"`
	// storage_cost ...
	StorageCost uint64 `protobuf:"varint,7,opt,name=storage_cost,json=storageCost,proto3" json:"storage_cost,omitempty"`
	// network_fee ...
	NetworkFee string `protobuf:"bytes,8,opt,name=network_fee,json=networkFee,proto3" json:"network_fee,omitempty"`
	// max_points ...
	MaxPoints uint64 `protobuf:"varint,9,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"`
	// unbonding_staking_time ...
	UnbondingStakingTime uint64 `protobuf:"varint,10,opt,name=unbonding_staking_time,json=unbondingStakingTime,proto3" json:"unbonding_staking_time,omitempty"`
	// unbonding_delegation_time ...
	UnbondingDelegationTime uint64 `protobuf:"varint,11,opt,name=unbonding_delegation_time,json=unbondingDelegationTime,proto3" json:"unbonding_delegation_time,omitempty"`
	// unbonding_delegation_time ...
	RedelegationCooldown uint64 `protobuf:"varint,12,opt,name=redelegation_cooldown,json=redelegationCooldown,proto3" json:"redelegation_cooldown,omitempty"`
	// unbonding_delegation_time ...
	RedelegationMaxAmount uint64 `protobuf:"varint,13,opt,name=redelegation_max_amount,json=redelegationMaxAmount,proto3" json:"redelegation_max_amount,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca08e39f277f4aef, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetVoteSlash() string {
	if m != nil {
		return m.VoteSlash
	}
	return ""
}

func (m *Params) GetUploadSlash() string {
	if m != nil {
		return m.UploadSlash
	}
	return ""
}

func (m *Params) GetTimeoutSlash() string {
	if m != nil {
		return m.TimeoutSlash
	}
	return ""
}

func (m *Params) GetUploadTimeout() uint64 {
	if m != nil {
		return m.UploadTimeout
	}
	return 0
}

func (m *Params) GetStorageCost() uint64 {
	if m != nil {
		return m.StorageCost
	}
	return 0
}

func (m *Params) GetNetworkFee() string {
	if m != nil {
		return m.NetworkFee
	}
	return ""
}

func (m *Params) GetMaxPoints() uint64 {
	if m != nil {
		return m.MaxPoints
	}
	return 0
}

func (m *Params) GetUnbondingStakingTime() uint64 {
	if m != nil {
		return m.UnbondingStakingTime
	}
	return 0
}

func (m *Params) GetUnbondingDelegationTime() uint64 {
	if m != nil {
		return m.UnbondingDelegationTime
	}
	return 0
}

func (m *Params) GetRedelegationCooldown() uint64 {
	if m != nil {
		return m.RedelegationCooldown
	}
	return 0
}

func (m *Params) GetRedelegationMaxAmount() uint64 {
	if m != nil {
		return m.RedelegationMaxAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "kyve.registry.v1beta1.Params")
}

func init() {
	proto.RegisterFile("kyve/registry/v1beta1/params.proto", fileDescriptor_ca08e39f277f4aef)
}

var fileDescriptor_ca08e39f277f4aef = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x6d, 0x35, 0x04, 0x3c, 0x4e, 0x58, 0x58, 0x2d, 0x1d, 0x90, 0x70, 0x4b, 0x11, 0x52,
	0x37, 0xd8, 0xaa, 0x8a, 0x58, 0x74, 0x07, 0xe5, 0xb2, 0x40, 0xa0, 0xaa, 0x45, 0x48, 0xb0, 0xb1,
	0xc6, 0xf6, 0xe0, 0x58, 0xb1, 0xe7, 0x58, 0x9e, 0xe3, 0xd4, 0x79, 0x0b, 0x96, 0x2c, 0x79, 0x1c,
	0x96, 0x5d, 0xb2, 0x42, 0x28, 0x79, 0x11, 0x34, 0x97, 0xe6, 0xb2, 0x4a, 0xf4, 0xfd, 0xdf, 0x7f,
	0xce, 0x8c, 0x35, 0xe4, 0x68, 0x3a, 0x9f, 0xf1, 0xb8, 0xe5, 0x45, 0x29, 0xb1, 0x9d, 0xc7, 0xb3,
	0x93, 0x94, 0x23, 0x3b, 0x89, 0x1b, 0xd6, 0xb2, 0x5a, 0x46, 0x4d, 0x0b, 0x08, 0xc1, 0x9e, 0x72,
	0xa2, 0x5b, 0x27, 0xb2, 0xce, 0xa3, 0xdd, 0x02, 0x0a, 0xd0, 0x46, 0xac, 0xfe, 0x19, 0xf9, 0xe8,
	0xef, 0x0e, 0x19, 0x5e, 0xe8, 0x76, 0xf0, 0x98, 0x90, 0x19, 0x20, 0x4f, 0x64, 0xc5, 0xe4, 0x84,
	0xee, 0x1c, 0xba, 0xc7, 0xde, 0xa5, 0xa7, 0xc8, 0x95, 0x02, 0xc1, 0x13, 0x32, 0xea, 0x9a, 0x0a,
	0x58, 0x6e, 0x85, 0x81, 0x16, 0x7c, 0xc3, 0x8c, 0xf2, 0x94, 0x8c, 0xb1, 0xac, 0x39, 0x74, 0x68,
	0x9d, 0x3b, 0xda, 0x19, 0x59, 0x68, 0xa4, 0x67, 0xe4, 0xbe, 0x9d, 0x63, 0x31, 0x1d, 0x1e, 0xba,
	0xc7, 0x83, 0xcb, 0xb1, 0xa1, 0x9f, 0x0d, 0x54, 0xeb, 0x24, 0x42, 0xcb, 0x0a, 0x9e, 0x64, 0x20,
	0x91, 0xde, 0xd5, 0x92, 0x6f, 0xd9, 0x39, 0x48, 0x0c, 0x0e, 0x88, 0x2f, 0x38, 0x5e, 0x43, 0x3b,
	0x4d, 0xbe, 0x73, 0x4e, 0xef, 0xe9, 0x65, 0xc4, 0xa2, 0x77, 0x9c, 0xab, 0x1b, 0xd5, 0xac, 0x4f,
	0x1a, 0x28, 0x05, 0x4a, 0xea, 0xe9, 0x09, 0x5e, 0xcd, 0xfa, 0x0b, 0x0d, 0x82, 0x17, 0xe4, 0x41,
	0x27, 0x52, 0x10, 0x79, 0x29, 0x8a, 0x44, 0x22, 0x9b, 0xaa, 0x5f, 0x75, 0x28, 0x4a, 0xb4, 0xba,
	0xbb, 0x4a, 0xaf, 0x4c, 0xa8, 0xce, 0x16, 0x9c, 0x91, 0x87, 0xeb, 0x56, 0xce, 0x2b, 0x5e, 0x30,
	0x2c, 0x41, 0x98, 0xa2, 0xaf, 0x8b, 0xfb, 0x2b, 0xe1, 0xcd, 0x2a, 0xd7, 0xdd, 0x53, 0xb2, 0xd7,
	0xf2, 0x8d, 0x4e, 0x06, 0x50, 0xe5, 0x70, 0x2d, 0xe8, 0xc8, 0x2c, 0xdc, 0x0c, 0xcf, 0x6d, 0x16,
	0xbc, 0x24, 0xfb, 0x5b, 0x25, 0x75, 0x25, 0x56, 0x43, 0x27, 0x90, 0x8e, 0x75, 0x6d, 0x6b, 0xe6,
	0x47, 0xd6, 0xbf, 0xd2, 0xe1, 0xd9, 0xe0, 0xe7, 0xaf, 0x03, 0xe7, 0xf5, 0xfb, 0xdf, 0x8b, 0xd0,
	0xbd, 0x59, 0x84, 0xee, 0xbf, 0x45, 0xe8, 0xfe, 0x58, 0x86, 0xce, 0xcd, 0x32, 0x74, 0xfe, 0x2c,
	0x43, 0xe7, 0xdb, 0xf3, 0xa2, 0xc4, 0x49, 0x97, 0x46, 0x19, 0xd4, 0xf1, 0x87, 0xaf, 0x5f, 0xde,
	0x7e, 0x32, 0x1f, 0x2e, 0xce, 0x26, 0xac, 0x14, 0x71, 0xbf, 0x7e, 0x65, 0x38, 0x6f, 0xb8, 0x4c,
	0x87, 0xfa, 0xc1, 0x9c, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xa3, 0x7a, 0x10, 0x83, 0x02,
	0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RedelegationMaxAmount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RedelegationMaxAmount))
		i--
		dAtA[i] = 0x68
	}
	if m.RedelegationCooldown != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RedelegationCooldown))
		i--
		dAtA[i] = 0x60
	}
	if m.UnbondingDelegationTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UnbondingDelegationTime))
		i--
		dAtA[i] = 0x58
	}
	if m.UnbondingStakingTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UnbondingStakingTime))
		i--
		dAtA[i] = 0x50
	}
	if m.MaxPoints != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPoints))
		i--
		dAtA[i] = 0x48
	}
	if len(m.NetworkFee) > 0 {
		i -= len(m.NetworkFee)
		copy(dAtA[i:], m.NetworkFee)
		i = encodeVarintParams(dAtA, i, uint64(len(m.NetworkFee)))
		i--
		dAtA[i] = 0x42
	}
	if m.StorageCost != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.StorageCost))
		i--
		dAtA[i] = 0x38
	}
	if m.UploadTimeout != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UploadTimeout))
		i--
		dAtA[i] = 0x30
	}
	if len(m.TimeoutSlash) > 0 {
		i -= len(m.TimeoutSlash)
		copy(dAtA[i:], m.TimeoutSlash)
		i = encodeVarintParams(dAtA, i, uint64(len(m.TimeoutSlash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.UploadSlash) > 0 {
		i -= len(m.UploadSlash)
		copy(dAtA[i:], m.UploadSlash)
		i = encodeVarintParams(dAtA, i, uint64(len(m.UploadSlash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.VoteSlash) > 0 {
		i -= len(m.VoteSlash)
		copy(dAtA[i:], m.VoteSlash)
		i = encodeVarintParams(dAtA, i, uint64(len(m.VoteSlash)))
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VoteSlash)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.UploadSlash)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.TimeoutSlash)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.UploadTimeout != 0 {
		n += 1 + sovParams(uint64(m.UploadTimeout))
	}
	if m.StorageCost != 0 {
		n += 1 + sovParams(uint64(m.StorageCost))
	}
	l = len(m.NetworkFee)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MaxPoints != 0 {
		n += 1 + sovParams(uint64(m.MaxPoints))
	}
	if m.UnbondingStakingTime != 0 {
		n += 1 + sovParams(uint64(m.UnbondingStakingTime))
	}
	if m.UnbondingDelegationTime != 0 {
		n += 1 + sovParams(uint64(m.UnbondingDelegationTime))
	}
	if m.RedelegationCooldown != 0 {
		n += 1 + sovParams(uint64(m.RedelegationCooldown))
	}
	if m.RedelegationMaxAmount != 0 {
		n += 1 + sovParams(uint64(m.RedelegationMaxAmount))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteSlash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteSlash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadSlash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UploadSlash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutSlash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeoutSlash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadTimeout", wireType)
			}
			m.UploadTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UploadTimeout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageCost", wireType)
			}
			m.StorageCost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageCost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPoints", wireType)
			}
			m.MaxPoints = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPoints |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingStakingTime", wireType)
			}
			m.UnbondingStakingTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingStakingTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingDelegationTime", wireType)
			}
			m.UnbondingDelegationTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingDelegationTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedelegationCooldown", wireType)
			}
			m.RedelegationCooldown = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RedelegationCooldown |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedelegationMaxAmount", wireType)
			}
			m.RedelegationMaxAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RedelegationMaxAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
